name: Update Weather in README

on:
  schedule:
    - cron: '0 */3 * * *' # Aggiorna ogni 3 ore
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Readme with Weather
        uses: matchai/weather-readme@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          LOCATION: "Piacenza, IT"
